package Calculator;


/**
* Calculator/CalcOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calc.idl
* jueves 2 de marzo de 2023 12H41' CET
*/

public interface CalcOperations 
{
  double calculate (int opcode, double op1, double op2);
  void exit ();
} // interface CalcOperations
