package Calculator;


/**
* Calculator/CalcOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calc.idl
* Wednesday, November 4, 2015 9:00:03 PM PST
*/

public interface CalcOperations 
{
  int calculate (int opcode, int op1, int op2);
  void exit ();
} // interface CalcOperations
